apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: digimon-digital-card-battle-guide
    tier: api
spec:
  selector:
    app: digimon-digital-card-battle-guide
    tier: api
  ports:
    - name: backend
      port: 3000
      protocol: TCP
  type: 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-api
  labels:
    app: digimon-digital-card-battle-guide
spec:
  accessModes: 
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: digimon-digital-card-battle-guide
spec:
  selector:
    matchLabels:
      app: digimon-digital-card-battle-guide
  template:
    metadata:
      name: backend
      labels:
        app: digimon-digital-card-battle-guide
        tier: api
    spec:
      containers:
        - name: backend
          image: digimon-digital-card-battle-guide_backend
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: volume-api
              mountPath: /var/www/html
      volumes:
        - name: volume-api
          persistentVolumeClaim:
            claimName: pv-claim-api