"""Initialize

Revision ID: 7d91b372c939
Revises: fdd9ed3be1e2
Create Date: 2025-08-10 15:40:35.512397

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d91b372c939'
down_revision = 'fdd9ed3be1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
