"""Initialize

Revision ID: fdd9ed3be1e2
Revises: 477e2c386a72
Create Date: 2025-07-21 07:13:38.051918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdd9ed3be1e2'
down_revision = '477e2c386a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
