"""Initialize

Revision ID: 477e2c386a72
Revises: 
Create Date: 2025-07-18 03:22:09.793871

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '477e2c386a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('FIRE', 'ICE', 'NATURE', 'DARKNESS', 'RARE', 'OPTION', name='cardtype'), nullable=False),
    sa.Column('lv', sa.Enum('R', 'C', 'U', 'A', name='cardlv'), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('dp', sa.Integer(), nullable=True),
    sa.Column('pow', sa.Integer(), nullable=True),
    sa.Column('circle', sa.Integer(), nullable=True),
    sa.Column('triangle', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('special_effect', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
