"""Initialize

Revision ID: bc28c7ab601f
Revises: 
Create Date: 2025-07-17 04:06:01.866458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc28c7ab601f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('type', sa.Enum('FIRE', 'ICE', 'NATURE', 'DARKNESS', 'RARE', 'OPTION', name='cardtype'), nullable=False),
    sa.Column('lv', sa.Enum('R', 'C', 'U', 'A', name='cardlv'), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('dp', sa.Integer(), nullable=True),
    sa.Column('pow', sa.Integer(), nullable=True),
    sa.Column('circle', sa.Integer(), nullable=True),
    sa.Column('triangle', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('special_effect', sqlmodel.sql.sqltypes.AutoString(length=93), nullable=True),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=376), nullable=False),
    sa.Column('img', sqlmodel.sql.sqltypes.AutoString(length=59), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
