apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: digimon-digital-card-battle-guide
    tier: database
spec:
  selector:
    app: digimon-digital-card-battle-guide
    tier: database
  ports:
    - port: 5432
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  labels:
    app: digimon-digital-card-battle-guide
spec:
  accessModes: 
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: digimon-digital-card-battle-guide
spec:
  selector:
    matchLabels:
      app: digimon-digital-card-battle-guide
      tier: database
  template:
    metadata:
      labels:
        app: digimon-digital-card-battle-guide
        tier: database
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PG_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PG_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PG_DB
          resources:
          volumeMounts:
            - name: volume-db
              mountPath: "/var/database"
      volumes:
        - name: volume-db
          persistentVolumeClaim:
            claimName: pvc-db
