name: Clean workflow runs

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Number of workflows runs'
        default: 100
        required: false
        type: number

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Delete
      run: |
          gh run list --json databaseId  -q '.[].databaseId' --limit ${{ github.event.inputs.limit }} | 
            xargs -IID gh api \
            "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" \
            -X DELETE 
      # env:
      #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
    # - name: Get and delete old workflow runs
    #   env:
    #       GH_REPO: ${{ github.repository }} # Automatically sets owner/repo
      # List workflow runs and filter for older ones (e.g., older than 30 days)
      # Adjust the 'jq' filter as needed to target specific workflows or statuses
      # run: |
      #     gh run list --limit 500 --json databaseId,createdAt,name \
      #       | jq -r '.[] | select((now - (.createdAt | fromdate)) > (1 * 24 * 60 * 60)) | .databaseId' \
      #       | while read run_id; do
      #           echo "Deleting run ID: $run_id"
      #           gh api -X DELETE "repos/$GH_REPO/actions/runs/$run_id"
      
