# https://docs.github.com/en/actions/how-tos/write-workflows
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
name: Test Workflow

on: [workflow_dispatch]
  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  # push:
  #   branches:
  #     - main

jobs:
  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run
  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do
  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/run-jobs-in-a-container
  runs-on: ubuntu-latest
  backend:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.15"
          enable-cache: true
  # frontend:
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         spec: |
  #           cypress/**/*.cy.js
  #     # after the test run completes store videos and any screenshots
  #     - uses: actions/upload-artifact@v4
  #       # add the line below to store screenshots only on failures
  #       # if: failure()
  #       with:
  #         name: cypress-screenshots
  #         path: cypress/screenshots
  #         if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: cypress-videos
  #         path: cypress/videos
  #         if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`





